# Generated by Django 2.1.5 on 2020-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player to move'), ('S', 'Second player to move'), ('W', 'First player wins'), ('L', 'Second player wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
